Open-Systems-Pharmacology/PK-Sim

- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.Assets/packages.config
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.BatchTool/packages.config
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Core/packages.config
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Infrastructure/packages.config
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Matlab/packages.config
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.Presentation/packages.config
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim.UI/UserSettings.cs
- src/PKSim.UI/packages.config
- src/PKSim/PKSim.csproj
- src/PKSim/packages.config
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.Tests/packages.config
- tests/PKSim.UI.Tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests/packages.config
Simple use of constant. Very similar to MoBi
> 109 default chart layout

- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.Assets/packages.config
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.BatchTool/packages.config
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Core/packages.config
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Infrastructure/app.config
- src/PKSim.Infrastructure/packages.config
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Matlab/packages.config
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.Presentation/app.config
- src/PKSim.Presentation/packages.config
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim.UI/app.config
- src/PKSim.UI/packages.config
- src/PKSim/PKSim.csproj
- src/PKSim/app.config
- src/PKSim/packages.config
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.Tests/app.config
- tests/PKSim.Tests/packages.config
- tests/PKSim.UI.Tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests/packages.config
Also updated the latest Core to get all bug fixes at the same time
> Fixes #184 Excel export/import stopped working

- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.BatchTool/packages.config
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim.UI/packages.config
- tests/PKSim.UI.Tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests/packages.config
This is pulling in an upgrade from DataBinding.DevExpress
> Fixes #165 - Binders overflow when binding large numbers

- src/PKSim.Infrastructure/ProjectConverter/v7_2/Converter710To720.cs
This is a try to fix issue with code coverage in #221
> Optimize parameter retrieval in 720 converter

- src/PKSim.Presentation/Presenters/PopulationAnalyses/PopulationAnalysisChartPresenter.cs
- src/PKSim.UI/Binders/ChartDataBinder.cs
This was indeed due to our refactoring for chart
> Fixes #357 zoom in population chart broken

- src/PKSim.Core/CoreConstants.cs
- tests/PKSim.Tests/IntegrationTests/PopulationRepositorySpecs.cs
- tests/PKSim.Tests/IntegrationTests/SimulationSpecs.cs
Once this PR is merged, pregnancy branch can be merged back into develop
> Fixes #368 Integrate pregnant population

- src/PKSim.Core/Batch/PopulationSettings.cs
- src/PKSim.Core/CoreConstants.cs
- src/PKSim.Presentation/DTO/Mappers/ParameterToParameterDTOMapper.cs
- tests/PKSim.Tests/Core/BatchPopulationSettingsToPopulationSettingsMapperSpecs.cs
- tests/PKSim.Tests/IntegrationTests/DatabaseUpdateSpecs.cs
- tests/PKSim.Tests/IntegrationTests/SimulationWithParticlesFormulationSpecs.cs
Fixes #583 Group Characteristics of Individual should be visible in SimpleMode
Fixes #533 Change case of parameter_name Reference Concentration in tab_molecule_parameters
> Fixes #605 Additional tests for particles dissolution

- src/PKSim.Assets/PKSimConstants.cs
- src/PKSim.Core/Snapshots/Mappers/PopulationAnalysisFieldMapper.cs
- src/PKSim.Core/Snapshots/Mappers/QuantityInfoMapper.cs
- src/PKSim.Core/Snapshots/PopulationAnalysisField.cs
- src/PKSim.Core/Snapshots/QuantityInfo.cs
- src/PKSim.Infrastructure/Serialization/Json/SnapshotSerializer.cs
- src/PKSim.Presentation/Core/LoadProjectFromSnapshotCommand.cs
- tests/PKSim.Tests/Core/PopulationAnalysisFieldMapperSpecs.cs
- tests/PKSim.Tests/Core/QuantityInfoMapperSpecs.cs
This is just better like that as discussed
> Fixes #706 Snapshot: Schema validation only for compound

- tests/PKSim.Tests/IntegrationTests/FlatParameterInContainsRepositorySpecs.cs
- tests/PKSim.Tests/ProjectConverter/v5_2/IndividualParameterConverterSpecs.cs
Fixes #522 flag IS_INPUT needs to be filled (was already done with previous commits)
Fixes #698 Integrate new ontogeny data for AGP
> Fixes #737 IS_INPUT not set properly

- src/PKSim.Core/Snapshots/Protocol.cs
> Fixes #788 snaspshot import problem with user defined app

- tests/PKSim.Tests/CoreConstantsForSpecs.cs
- tests/PKSim.Tests/IntegrationTests/DatabaseUpdateSpecs.cs
- tests/PKSim.Tests/IntegrationTests/ValueOriginRepositorySpecs.cs
Fixes #704 Value Origin: Source may not be UNDEFINED if description is provided
> Fixes #819 Finalize value origins for 7.3

- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Infrastructure/Serialization/Json/ColorConverter.cs
- src/PKSim.Infrastructure/Serialization/Json/PKSimJsonSerializerSetings.cs
- tests/PKSim.Tests/Infrastructure/SnapshotSerializerSpecs.cs
@Yuri05 It seems that loading from HEX Numbers works out of the box
> Fixes #1090 json color

- src/PKSim.Infrastructure/ORM/Queries/ModelObserverQuery.cs
- tests/PKSim.Tests/CoreConstantsForSpecs.cs
- tests/PKSim.Tests/IntegrationTests/ModelObserverQuerySpecs.cs
> Fixes #1146 add observer to build configuration

- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.Assets/packages.config
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.BatchTool/packages.config
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI.Core/packages.config
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.CLI/packages.config
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Core/packages.config
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Infrastructure/packages.config
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Matlab/packages.config
- src/PKSim.Presentation/DTO/Core/RenameObjectDTOFactory.cs
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.Presentation/Presenters/Individuals/CreateIndividualPresenter.cs
- src/PKSim.Presentation/packages.config
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim.UI/packages.config
- src/PKSim/PKSim.csproj
- src/PKSim/packages.config
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.Matlab.Tests/packages.config
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.Tests/packages.config
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
- tests/PKSim.UI.Tests/packages.config
@Yuri05 Actually it's already doing it. So just updating dependencies here
> Fixes #1133 markdown for simulation

- src/PKSim.Infrastructure/ProjectConverter/v8_0/Converter740To80.cs
- tests/PKSim.Tests/ProjectConverter/v8_0/Converter740To80Specs.cs
> Fixes #1272

- src/Db/Diff/PKSimDB_diff.txt
@msevestre Batch-Runs must be repeated then
> Fixes #1478 Equation for transfer rate from plasma of small / large intestine to mucosa plasma compartments

- appveyor.yml
- src/PKSim.Core/CoreConstants.cs
- src/PKSim.Core/Services/CompetitiveInhibitionsKineticUpdaterSpecification.cs
- src/PKSim.Core/Services/InteractionKineticUpdaterSpecificationBase.cs
- src/PKSim.Core/Services/InteractionTask.cs
- src/PKSim.Core/Services/IrreversibleInhibitionKineticUpdaterSpecification.cs
- src/PKSim.Core/Services/MixedInhibitionKineticUpdaterSpecification.cs
- src/PKSim.Core/Services/NonCompetitiveInhibitionKineticUpdaterSpecification.cs
- src/PKSim.Core/Services/UncompetitiveInhibitionKineticUpdaterSpecification.cs
- tests/PKSim.Tests/Core/CompetitiveInhibitionsKineticUpdaterSpecificationSpecs.cs
- tests/PKSim.Tests/Core/IrreversibleInhibitionKineticUpdaterSpecificationSpecs.cs
- tests/PKSim.Tests/Core/MixedInhibitionKineticUpdaterSpecificationSpecs.cs
- tests/PKSim.Tests/Core/NonCompetitiveInhibitionKineticUpdaterSpecificationSpecs.cs
- tests/PKSim.Tests/Core/UncompetitiveInhibitionKineticUpdaterSpecificationSpecs.cs
@Yuri05 Please review asap. Going to perform some tests
> Fixes #1523 wrong interation factor

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
Release candidate for testing purposes
> V10 prerelease

- src/PKSim.CLI.Core/Services/ExportSimulationRunner.cs
- src/PKSim.CLI.Core/Services/QualificationRunner.cs
- src/PKSim.CLI.Core/Services/SimulationExporter.cs
- tests/PKSim.Tests/CLI/ExportSimulationRunnerSpecs.cs
- tests/PKSim.Tests/CLI/QualificationRunnerSpecs.cs
> Export pkml qualification

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
> updating packages

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Infrastructure/Services/ImportObservedDataTask.cs
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
Fixes #1782 (Fires event on DataRepository reloaded)
> Update core and fire event

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/MinimalImplementations/CLIDataImporter.cs
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Core/Services/CompoundAlternativeTask.cs
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Infrastructure/Services/ImportObservedDataTask.cs
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.Presentation/Services/FormulationTask.cs
- src/PKSim.Presentation/Services/IndividualOntogenyTask.cs
- src/PKSim.Presentation/Services/OntogenyTask.cs
- src/PKSim.Presentation/Services/PopulationOntogenyTask.cs
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/Core/OntogenyTaskSpecs.cs
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.Tests/Presentation/CompoundAlternativeTaskSpecs.cs
- tests/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
> Plugging in the new dlls

- src/PKSim.Assets/PKSimConstants.cs
- src/PKSim.BatchTool/BatchUserSettings.cs
- src/PKSim.Infrastructure/Serialization/Xml/Serializers/UserSettingsXmlSerializer.cs
- src/PKSim.Presentation/Presenters/Charts/ChartPresenter.cs
- src/PKSim.Presentation/Presenters/Charts/IndividualSimulationComparisonPresenter.cs
- src/PKSim.Presentation/Presenters/Charts/SimulationTimeProfileChartPresenter.cs
- src/PKSim.Presentation/Presenters/ContextMenus/ObservedDataFolderContextMenu.cs
- src/PKSim.UI/UserSettings.cs
- src/PKSim.UI/Views/UserSettingsView.Designer.cs
- src/PKSim.UI/Views/UserSettingsView.cs
- tests/PKSim.Tests/Presentation/IndividualSimulationComparisonPresenterSpecs.cs
- tests/PKSim.Tests/Presentation/SimulationTimeProfileChartPresenterSpecs.cs
> color grouping by dropping to chart implemented

- src/PKSim.UI/Views/ProteinExpression/ExpressionDataView.cs
@Yuri05 I tried at least 20 different enzymes between v10 and v11 and never get a difference in the graph
So until you find one that is different, I am considering it a **VERY GOOD AND SECURE** fix :)
> Get a graph again

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/MinimalImplementations/CLIDataImporter.cs
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Infrastructure/Services/ImportObservedDataTask.cs
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
> 2061 importer dimensions

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Infrastructure/Services/ImportObservedDataTask.cs
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
> 2073 molweight correction

- src/PKSim.UI/Binders/TimeProfileChartDataBinder.cs
- src/PKSim.UI/Views/PopulationAnalyses/BaseChartView.cs
@Yuri05 Unified with time profile for individual curved
> Fixes #1522 symbol does not match

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/Core/OpenSingleStartPresenterInvoker.cs
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.Presentation/Presenters/Main/MenuAndToolBarPresenter.cs
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.Tests/Presentation/MenuAndToolBarPresenterSpecs.cs
- tests/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
Fixes #1901 (Multiple PI in parallel)
> Multiple PI in parallel

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
closes #2090
@msevestre I saw that your last commit updated the packages too, but the handling of invalid files was not included i that version of Core.
> updating nugets

- src/PKSim.Assets/PKSimConstants.cs
- src/PKSim.Core/Model/Template.cs
- src/PKSim.Core/Services/Formatter.cs
- src/PKSim.Presentation/DTO/TemplateDTO.cs
- src/PKSim.Presentation/Presenters/TemplatePresenter.cs
- src/PKSim.UI/Views/TemplateView.Designer.cs
- src/PKSim.UI/Views/TemplateView.cs
- src/PKSim.UI/Views/TemplateView.resx
- tests/PKSim.Tests/Core/FormatterSpecs.cs
- tests/PKSim.Tests/Presentation/TemplatePresenterSpecs.cs
> Fixes #2105 qualified status

- src/PKSim.Core/Services/SimulationPersistableUpdater.cs
- src/PKSim.Core/Services/SimulationRunner.cs
- tests/PKSim.Tests/Core/SimulationPersistableUpdaterSpecs.cs
Makes sure the population simulation also have the required outputs
> Default outputs population simulations

- src/PKSim.Assets/PKSimConstants.cs
- src/PKSim.Core/Extensions/EnumerableExtensions.cs
- src/PKSim.Core/Mappers/PKValuesToPKAnalysisMapper.cs
- src/PKSim.Core/Mappers/PopulationPKAnalysisToDataTableMapper.cs
- src/PKSim.Core/Model/FloatMatrix.cs
- src/PKSim.Core/Services/ChartsDataCreator.cs
- src/PKSim.Core/Services/GlobalPKAnalysisTask.cs
- src/PKSim.Core/Services/PKAnalysesTask.cs
- src/PKSim.Core/Services/TimeProfileChartsDataCreator.cs
- src/PKSim.Presentation/Core/SingleStartPresenterTask.cs
- src/PKSim.Presentation/DTO/Simulations/PKAnalysisDTO.cs
- src/PKSim.Presentation/Presenters/Charts/EditTimeProfileAnalysisChartPresenter.cs
- src/PKSim.Presentation/Presenters/Simulations/PopulationPKAnalysisPresenter.cs
- src/PKSim.Presentation/Views/Simulations/IPopulationPKAnalysisView.cs
- src/PKSim.UI/Views/Simulations/GlobalPKAnalysisView.Designer.cs
- src/PKSim.UI/Views/Simulations/GlobalPKAnalysisView.cs
- src/PKSim.UI/Views/Simulations/PopulationPKAnalysisView.Designer.cs
- src/PKSim.UI/Views/Simulations/PopulationPKAnalysisView.cs
- tests/PKSim.Tests/Core/FloatMatrixSpecs.cs
- tests/PKSim.Tests/Core/PKAnalysesTaskSpecs.cs
- tests/PKSim.Tests/Core/TimeProfileChartsDataCreatorSpecs.cs
- tests/PKSim.Tests/Infrastructure/PopulationPKAnalysesTaskSpecs.cs
- tests/PKSim.Tests/Presentation/EditTimeProfileAnalysisChartPresenterSpecs.cs
- tests/PKSim.Tests/Presentation/PopulationPKAnalysisPresenterSpecs.cs
Fixes having two tabs, one for calculations based on aggregated curve and one for calculations directly aggregated from individuals
> Adding two ways of aggregate on populations

- src/PKSim.UI/Views/Charts/EditTimeProfileAnalysisChartView.cs
- src/PKSim.UI/Views/Simulations/PopulationPKAnalysisView.Designer.cs
- src/PKSim.UI/Views/Simulations/PopulationPKAnalysisView.cs
@PavelBal For some re4asons, some code was removed during a merge. Putting it back
> Fixes #2318 tab empty

- src/PKSim.Assets/PKSimConstants.cs
I think this description is more clear.
> Fixes #2377 Reword global PK Analysis description

- src/PKSim.Core/Services/PKAnalysesTask.cs
Change all ratio parameters to fraction dimension
> Fixes #2409 Error when adding Bioavailability

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/Chart/IndividualSimulationComparison.cs
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.Presentation/Presenters/Charts/ChartPresenter.cs
- src/PKSim.Presentation/Presenters/Charts/IndividualSimulationComparisonPresenter.cs
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
> 2438 outptu mappings not cleared

- src/PKSim.Presentation/Presenters/Simulations/ConfigureSimulationPresenter.cs
- tests/PKSim.Tests/Presentation/ConfigureSimulationPresenterSpecs.cs
> 2592 Output Mapping duplication in cloning solved

- src/PKSim.Core/CoreConstants.cs
- src/PKSim.Core/Services/IMoBiExportTask.cs
- src/PKSim.Infrastructure/Services/MoBiExportTask.cs
- src/PKSim.Presentation/UICommands/GeneratePKMLTemplatesCommand.cs
- tests/PKSim.Tests/Infrastructure/MoBiExportTaskSpecs.cs
I think I remember we said we'd give it some more time and if no one has an opinion, we would pull the trigger on this topic.
Also - https://github.com/Open-Systems-Pharmacology/MoBi/issues/534
> Fixes #2681 MoBi creates much more containers than PK-Sim

- src/PKSim.Core/Mappers/ExpressionProfileToExpressionProfileBuildingBlockMapper.cs
- src/PKSim.Core/Mappers/IndividualToIndividualBuildingBlockMapper.cs
- src/PKSim.Core/Mappers/PathAndValueBuildingBlockMapper.cs
- src/PKSim.Core/Model/IndividualParameterSameFormulaOrValueForAllSpecies.cs
- src/PKSim.Core/Model/SimulationFactory.cs
- src/PKSim.Core/Repositories/IIndividualParametersSameFormulaOrValueForAllSpeciesRepository.cs
- src/PKSim.Core/Services/MoleculeOntogenyVariabilityUpdater.cs
- src/PKSim.Core/Services/ParameterContainerTask.cs
- src/PKSim.Infrastructure/ORM/FlatObjects/FlatIndividualParametersSameFormulaOrValueForAllSpecies.cs
- src/PKSim.Infrastructure/ORM/Repositories/IndividualParametersSameFormulaOrValueForAllSpeciesRepository.cs
- src/PKSim.Infrastructure/ORM/Repositories/OntogenyRepository.cs
- src/PKSim.Presentation/Services/OntogenyTask.cs
- tests/PKSim.Tests/Core/ExpressionProfileToExpressionProfileBuildingBlockMapperSpecs.cs
- tests/PKSim.Tests/Core/MoleculeOntogenyVariabilityUpdaterSpecs.cs
- tests/PKSim.Tests/IntegrationTests/IndividualParametersSameFormulaOrValueForAllSpeciesRepositorySpecs.cs
- tests/PKSim.Tests/IntegrationTests/SimulationSpecs.cs
@Yuri05 WIP but my local does not run tests anymore and I don't know why
> Fixes #2770

- .github/PULL_REQUEST_TEMPLATE.md
- appveyor.yml
> one more change on the PR template

- src/PKSim.Presentation/Presenters/Snapshots/LoadFromSnapshotPresenter.cs
- src/PKSim.Presentation/Presenters/Snapshots/LoadProjectFromSnapshotPresenter.cs
- src/PKSim.Presentation/Presenters/Snapshots/LoadSimulationFromSnapshotPresenter.cs
- src/PKSim.Presentation/Views/Snapshots/ILoadFromSnapshotView.cs
- src/PKSim.UI/Views/Snapshots/LoadFromSnapshotView.cs
- tests/PKSim.Tests/Presentation/LoadFromSnapshotPresenterSpecs.cs
- tests/PKSim.Tests/Presentation/LoadProjectFromSnapshotPresenterSpecs.cs
Fixes #2820
https://github.com/Open-Systems-Pharmacology/docs
https://github.com/Open-Systems-Pharmacology/developer-docs
> Fixes #2820 make run simulation visibible for everyone

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI.Core/Services/JsonSimulationRunner.cs
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
Fixes #2787 
Just a core update
> Fixes #2787

- src/PKSim.Core/Model/Simulation.cs
- src/PKSim.Presentation/Presenters/Main/SimulationExplorerPresenter.cs
- tests/PKSim.Tests/IntegrationTests/SimulationSpecs.cs
- tests/PKSim.Tests/Presentation/SimulationExplorerPresenterSpecs.cs
Fixes #2817
We don't use Single anymore but first
https://github.com/Open-Systems-Pharmacology/docs
https://github.com/Open-Systems-Pharmacology/developer-docs
> Fixes #2817 simulation create subfolder by comppund

- .github/PULL_REQUEST_TEMPLATE.md
- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/Commands/UpdateDistributedTableFormulaPercentileCommand.cs
- src/PKSim.Core/Commands/UpdateDistributedTableFormulaRatioCommand.cs
- src/PKSim.Core/Mappers/IndividualToIndividualBuildingBlockMapper.cs
- src/PKSim.Core/Model/PopulationSimulation.cs
- src/PKSim.Core/Model/UserDefinedOntogeny.cs
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Core/Services/SimulationConfigurationValidator.cs
- src/PKSim.Core/Snapshots/Mappers/TableFormulaMapper.cs
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.Presentation/Presenters/Parameters/TableParameterPresenter.cs
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/Core/TableFormulaMapperSpecs.cs
- tests/PKSim.Tests/Core/UpdateDistributedTableFormulaPercentileCommandSpecs.cs
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.Tests/Presentation/CompoundAlternativeTaskSpecs.cs
- tests/PKSim.Tests/Presentation/TableParameterPresenterSpecs.cs
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
Fixes #2826
Fixes #2825
There are some errors calculating display values for ExtendedParameters when mapping an individual to an individual building block. We need to do display unit conversions and modify the calculation method extended property display value
Also, core update included
> Issues with origin data

- src/PKSim.Infrastructure/Services/MoBiExportTask.cs
> Fixes #2751 and Fixes #2750

- src/PKSim.Core/Mappers/IndividualToIndividualBuildingBlockMapper.cs
- src/PKSim.Core/Snapshots/Mappers/ProjectMapper.cs
Fixes #2836
Crashing during qualification run
> Fixes #2836 export to invidual crashes

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
> update core and simmodel

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/Model/ApplicationFactory.cs
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Core/Services/DataRepositoryFromResultsCreator.cs
- src/PKSim.Core/Services/ParticleApplicationCreator.cs
- src/PKSim.Infrastructure/ORM/Mappers/FlatRelativeObjectPathToObjectPathMapper.cs
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Infrastructure/Serialization/Xml/Serializers/ObjectPathXmlAttributeMapper.cs
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/Core/DataRepositoryFromResultsCreatorSpecs.cs
- tests/PKSim.Tests/IntegrationTests/PartialProcessesSpecs.cs
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
Just a core update
Just keeping core sync among the apps 
> update core to 12.0.257

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
> Fixes #2840

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
Fixes #
Simple core update to the latest
> Update core to latest

- appveyor-nightly.yml
- appveyor.yml
- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
> Update core and version numbers

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim.UI/Views/ProteinExpression/ProteinSelectionView.cs
- src/PKSim.UI/Views/ProteinExpression/TransferView.cs
- src/PKSim.UI/Views/Simulations/PKAnalysisPivotView.cs
- src/PKSim/PKSim.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
Fixes #
Initialize component and target new package
> #1301 - Initialize component and target new package

- appveyor-nightly.yml
Changing the .NET version for creating the dependency artifact on AppVeyor.
> Update target framework for dependency resolution project

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- src/PKSimRDependencyResolution/PKSimRDependencyResolution.csproj
- src/PKSimRDependencyResolution/excludedFiles.txt
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
Fixes #2923
Update references for ubuntu native libraries
> 2923 package ubuntu native shared libraries with dependency resolver project

- appveyor-nightly.yml
- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Infrastructure/PKSimConfiguration.cs
- src/PKSimRDependencyResolution/PKSimRDependencyResolution.csproj
Fixes #2931
Some small changes to allow initializing of PKSim.R in Ubuntu
> 2931 initialize pk simr in ubuntu

- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- src/PKSimRDependencyResolution/PKSimRDependencyResolution.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
Updating a dependency on System.Data.SQlite.core
> update System.Data.SQLite and fix csproj.

- src/PKSim.Assets.Images/PKSim.Assets.Images.csproj
- src/PKSim.Assets/PKSim.Assets.csproj
- src/PKSim.BatchTool/PKSim.BatchTool.csproj
- src/PKSim.CLI.Core/PKSim.CLI.Core.csproj
- src/PKSim.CLI/PKSim.CLI.csproj
- src/PKSim.Core/PKSim.Core.csproj
- src/PKSim.Infrastructure/PKSim.Infrastructure.csproj
- src/PKSim.Infrastructure/ProjectConverter/v12/Converter11To12.cs
- src/PKSim.Matlab/PKSim.Matlab.csproj
- src/PKSim.Presentation/PKSim.Presentation.csproj
- src/PKSim.R/PKSim.R.csproj
- src/PKSim.UI.Starter/PKSim.UI.Starter.csproj
- src/PKSim.UI/PKSim.UI.csproj
- src/PKSim/PKSim.csproj
- src/PKSimRDependencyResolution/PKSimRDependencyResolution.csproj
- tests/PKSim.Matlab.Tests/PKSim.Matlab.Tests.csproj
- tests/PKSim.R.Tests/PKSim.R.Tests.csproj
- tests/PKSim.Tests/PKSim.Tests.csproj
- tests/PKSim.UI.Tests/PKSim.UI.Tests.csproj
Fixes #2936 
Project conversion and core update
> Fixes #2936 remove parameterbuildmode = property

- src/PKSim.Assets/PKSimConstants.cs
- src/PKSim.Core/Snapshots/Mappers/ProjectMapper.cs
- tests/PKSim.Tests/Core/ProjectMapperSpecs.cs
> Fixes #2965

- src/PKSim.CLI.Core/RunOptions/SnapshotRunOptions.cs
- src/PKSim.CLI.Core/Services/SnapshotRunner.cs
> Fixes #2968 Allow Snapshot Runner to bypass running simulations

- src/PKSim.Core/Snapshots/Project.cs
- src/PKSim.Infrastructure/ProjectConverter/v9/Converter8To9.cs
- src/PKSim.Infrastructure/Services/NeighborhoodFinalizer.cs
- tests/PKSim.Tests/Core/BoxWhiskerChartsDataCreatorSpecs.cs
- tests/PKSim.Tests/Core/SnapshotProjectSpecs.cs
- tests/PKSim.Tests/IntegrationTests/IndividualEnzymeFactorySpecs.cs
- tests/PKSim.Tests/IntegrationTests/IndividualParameterBySpeciesRepositorySpecs.cs
Fixes #3015
We have a special case to deal with regarding expression profiles => use composite keys
> Fixes #3015

- src/PKSim.Core/Services/DistributedParameterToTableParameterConverter.cs
- tests/PKSim.Tests/IntegrationTests/SimulationSpecs.cs
> Fixes #3052 Editing of parameters with aging in simulation

- src/PKSim.Core/Mappers/IndividualToIndividualBuildingBlockMapper.cs
- src/PKSim.Core/Mappers/PathAndValueBuildingBlockMapper.cs
- tests/PKSim.Tests/IntegrationTests/SimulationSpecs.cs
> Fixes #3065
